baseURL = '/'
languageCode = 'en-us'
title = 'd'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[markup]
  [markup.highlight]
    lineNumbersInTable = true


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
