name = 'deb hugo theme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'my personal hugo theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dai-re/deb-hugo-theme'

# If you have a running demo of the theme
demosite = 'https://daire.ru.org/archive'

# Taxonomy terms
tags = ['blog', 'company']
features = ['fast', 'simple', 'features']


# If the theme has a single author
[author]
  name = 'dai re'
  homepage = 'http://daire.eu.org'
